### ISSUE TITLE
Hall of Fame

### ISSUE THREAD

**Issue by Maelstromeous** [Maelstrome26/PS2Alerts#28]
Hall of Fame, highlighting things such as:

Definates:
- Top Farmers (top by kills)
- Top Crops (top by deaths)
- Top Backstabbers (top by TKs)
- Top Daredevil (top by suicides) - may change name of this to prevent {{triggers}}
- Top Outfits (by kills initially)
- Top Outfits by Captures
- Top Vehicles - will see if server filtering is possible
- Top Weapons - will see if server filtering is possible
- Top Alerts by Kills, Deaths, Tks and Suicides
- Most contested facilities

Possibles:
- Top Tanker (top by Tank to everything)
- Top Ace (top by ESF to ESF kills) - might be a bit difficult but I'll try
- Top Medic
- Top Platoon leader - possibly, depends how hard the data is to get
- Top Classes (top players by each class by metrics (kills initially))
- Top Players by Sanctioned Weapon kills - this is an interesting one... does anyone have a definitive list of what is classed as a "Sanctioned Weapon"?
- Top Cheese Grater - Top MAX players
- Top Ammo Donkey
- Top Tank Mine Tosser
- Sticky Gren Supremo
- Top Welder
- Turret Meister - kills with MANA turret
- Pocket Engi (Top max repairs)
- Bubble Gum Vendor (Top medic bubble shield points)
- Necromancer (Top revives)
- On point (Top point captures)

Suggestions:
- Top players by kills with sanctioned weapons
- Top vehicle killer - need to confirm I collect this info
- Have monthly, weekly and daily leaderboards

Etc

**Comment by Maelstromeous** [comment]
Added more things to the list, as per the reddit discussion:

https://www.reddit.com/r/Planetside/comments/478gpz/ps2alerts_working_on_leaderboard_system_post_your/

**Comment by Maelstromeous** [comment]
Now going to refer this section as the "Hall of Fame" as Leaderboards are often getting confused with the Alert Detail Leaderboards.

**Comment by Maelstrome26** [comment]
Figured out format - 5 Tabs as seperate pages

# Tab 1 - Top 10

Shows all top 10 of players, outfits, weapons and vehicles (although there's no 10 vehicles.)

# Tab 2 - Players Leaderboard

Shows ALL players (paginated) and their position. Will have to calculate the positions in Javascript, that's way too much work for the API to do.

Will have to develop API endpoint to accept order direction and fields.

# Tab 3 - Outfit Leaderboard 

Same format as players.

# Tab 4 - Weapon Leaderboard

Same format as players.

# Tab 5 - Vehicle Leaderboard

Shows statistics for all vehicles, but not by player (since those stats are borked).
